version: '3.9'

services:
  goph-keeper-postgres:
    container_name: goph-keeper-postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - goph-keeper-pgsql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=gkeeper
      - POSTGRES_DB=goph-keeper

volumes:
  goph-keeper-pgsql:
    external: true